<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
	<ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <RootNamespace>EMSME</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x64</Platforms>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <StartupObject>EMSME.Program</StartupObject>
    <AssemblyTitle>$(MSBuildProjectName)</AssemblyTitle>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
    <Title>EMS manual error</Title>
    <Company>Sebastian Lang</Company>
    <Description>A simple button for EMC susceptibility test software to trigger EUT errors manually.
This tool was originally developed for R&amp;S®ELEKTRA. However, it is compatible with any EMS software that can integrate monitoring devices or tools via TCP/IP and SCPI commands.
"EMS manual error" is highly customizable for maximum compatablity with other software and ease of use according to your needs.</Description>
    <Copyright>Sebastian Lang</Copyright>
    <PackageProjectUrl>https://github.com/SebastianLang-GER/ems-manual-error</PackageProjectUrl>
    <PackageIcon>Icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/SebastianLang-GER/ems-manual-error</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>ELEKTRA;EMC32;EMC;EMS</PackageTags>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DebugType>full</DebugType>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DebugType>full</DebugType>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\Graphics\Icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>